[package]
name = "ZeroGPU"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "26.0"
bytemuck = { version = "1.4", features = ["derive"] }
winit = "0.30"
pollster = "0.4"
env_logger = "0.11.8"

