[package]
name = "ZeroEditor"
version = "0.1.0"
edition = "2024"


[dependencies]
anyhow = "1.0.99"

bytemuck = { version = "1.14", features = ["derive"] }
glam = "0.30.5"

iced = { version = "0.13.1", features = ["advanced", "wgpu"] }
iced_winit = "0.13.0"
serde = "1.0.219"
serde_json = "1.0.143"
